# set pallet
palette = "catppuccin_latte"

add_newline = false
format = """
[](fg:mauve)\
$os\
$username\
$directory\
[](fg:red)\
$character\
"""
right_format = """
[](fg:peach)\
$git_branch\
$git_status\
[](bg:green fg:peach)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$package\
[](bg:sky fg:green)\
$docker_context\
[](bg:blue fg:sky)\
$time\
[ ](fg:blue)\
"""
command_timeout = 1000

# format = """
# [](mauve)\
# $os\
# $username\
# [](bg:red fg:mauve)\
# $directory\
# [](bg:peach fg:red)\
# $git_branch\
# $git_status\
# [](bg:green fg:peach)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [](bg:sky fg:green)\
# $docker_context\
# [](bg:blue fg:sky)\
# $time\
# [ ](fg:blue)\
# """

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:mauve"
style_root = "bg:mauve"
format = '[$user󰽥 ]($style)'
disabled = false


# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:mauve"
format = '[  ]($style)'
disabled = false # Disabled by default

[directory]
style = "bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[package]
style = "bg:green"
format = '[ $symbol$version]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:sky"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:peach"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:peach"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:green"
format = '[ $symbol ]($style)'

[gradle]
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:blue"
format = '[ $time ]($style)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

